version: '3'

services:
  app:
    image: docker-nextjs-dev
    build: .
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./_posts:/app/_posts
      - ./@types:/app/@types
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "8000:8000"