version: '3'
services:
  webapp01:
    container_name: webapp01
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/next-blog
    command: sh -c "cd next-blog && npm run dev"
    ports:
      - 3000:3000