version: '3'

services:
  app:
    image: docker-nextjs-dev
    ports:
      - "3000:3000"
    build: .
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./_posts:/app/_posts
      - ./@types:/app/@types