backend:
  name: git-gateway
  repo: docker-next-blog
  branch: main

media_folder: "public/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: ''}
      - {label: "Excerpt", name: "excerpt", widget: "string", default: ''}
      - {label: "Cover Image", name: "coverImage", widget: "string", default: ''}
      - {label: "Publish Date", name: "date", widget: "datetime", format: 'YYYY-MM-DD'}
      - label: "OG Image"
        name: "ogImage"
        widget: "object"
        fields:
          - {label: "URL", name: "url", widget: "string", default: ''}
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: {label: "Tag", name: "tag", widget: "string"}
      - {label: "Body", name: "body", widget: "text"}
