name: Deploy to GitHub Pages

on:
  push:
  repository_dispatch:
    types: [update-articles]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.8.0'
          cache: npm
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            
      - name: Install dependencies
        run: npm install

      - name: Update Articles
        run: node update-articles.js
        env:
          MICRO_CMS_API_KEY: ${{ secrets.MICRO_CMS_API_KEY }}
          MICRO_CMS_API_BASE_URL: ${{ secrets.MICRO_CMS_API_BASE_URL }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}

      - name: Commit and push changes
        run: |
          git config user.name "Gaku52"
          git config user.email "gaku.o.engineer@gmail.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update articles"
          git push

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_ROOT_URL: ${{ secrets.NEXT_PUBLIC_ROOT_URL }}
          NEXT_PUBLIC_SITE_NAME: ${{ secrets.NEXT_PUBLIC_SITE_NAME }}
  
      - name: Move 404 to root
        run: mv ./out/404/index.html ./out/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: out
